In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)

1
(5,)
int32


In [19]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)
print(arr2.itemsize)
print(arr2.nbytes)
print(arr2.size)

2
(2, 4)
int32
4
32
8


In [20]:
arr3 = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [22]:
print(arr3)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
print(arr3[1, 5])

13


In [24]:
print(arr3[0, :])

[1 2 3 4 5 6 7]


In [25]:
print(arr3[:, 2])

[ 3 10]


In [26]:
print(arr3[0, 1:-1:2])

[2 4 6]


In [28]:
arr3[1, 5] = 20
print(arr3)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
arr3[:, 2] = [1, 2]
print(arr3)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [31]:
arr4 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr4.ndim)
print(arr4)

3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
print(arr4[0, 1, 1])

4


In [34]:
arr4[:, 1, :] = [[9, 9], [8, 8]]
print(arr4)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [37]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones((4, 2, 2), dtype=int)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [40]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [42]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [43]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [44]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([2, 2, 2, 2, 2, 2, 2])
print(a)
print(b)
print(a * b)

[1 2 3 4 5 6 7]
[2 2 2 2 2 2 2]
[ 2  4  6  8 10 12 14]


In [45]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([2, 2, 2, 2, 2, 2, 2, 2])
print(a)
print(b)
print(a * b)

[1 2 3 4 5 6 7]
[2 2 2 2 2 2 2 2]


ValueError: operands could not be broadcast together with shapes (7,) (8,) 

In [48]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.array([2, 2, 2, 2])
print(a)
print(b)
print(a + b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[2 2 2 2]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [49]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print(a)
print(b)
print(a + b)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]
